[package]
name = "cala-docs"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

[dependencies]
comrak = "0.10"
# pulldown-cmark = { version = "0.5", default-features = false, features = ["simd"] }
